### ISSUE TITLE
Not found images in assets when use flet pack

### ISSUE THREAD

**Issue by mars1211** [ndonkoHenri/Flet-as-System-Tray-Icon#1]
Not found icon in my case if i run executed file

```
from PIL import Image

self.tray_image = Image.open("assets/icons/logo.png")
...
flet.app(target=root, assets_dir="assets")
```

for build i use command
``` 
flet pack .\main.py --icon .\assets\icons\favicon.png --add-data "assets;assets"  
```

> [Errno 2] No such file or directory: 'assets/icons/logo.png'

**Comment by ndonkoHenri** [comment]
Does the program work good already? (i mean before trying to `flet pack` it)

**Comment by ndonkoHenri** [comment]
Sorry/ Closed by mistake.

**Comment by mars1211** [comment]
I found soluton:

To access them, add this fucntion to your main.py (or helper) file:

```
import os

def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
```

Then, every time you would use the file name "image.png", replace it with 

> resource_path("image.png")


sys._MEIPASS - its temparary folder when you build program in one file

**Comment by ndonkoHenri** [comment]
I tried your solution, but it also failed. This was because it used the current working directory to generate the absolute path of the image. And PyInstaller changed that while building to `C:\.......\dist` and hence adding the relative path can't find the image (because it is not in the `dist` folder).
Anyway, what I did to solve this issue, was simply to directly use an absolute path (`Image.open(r"C:\..............\assets\icons\logo.png")`) to my image instead of a relative path. (this is kind of what your function does)
Thanks for your feedback on this.
